export const configRouter = {
  home: "/",
  register: "/register",
  login: "/login",
  specificCourse: "/specificCourse/:course",
  learnings: "/learnings/sublesson/:sublesson",
  quiz: "/learnings/sublesson/exam/quiz/:quizId",
  payment: "/payment/course/:courseId/category/:categorySecondId/",
  profile: "/profile",
  teacher: "/teacher/:teacherId",
  CourseCategory: "/courseCategory/:categoryId/:categorySecondId",
  CourseMe: "/courseMe",
  HistoryLearn: "/HistoryLearn",
  ForgetPassword: "/ForgetPassword",
};
